const initialState = {
  items: [
    {
      id: 1,
      title: "Napster Metal Queen Bed (6x5)",
      price: {
        threeMonths: 319,
        sixMonths: 219,
        twelveMonths: 119,
      },
      image: "https://p.rmjo.in/productSquare/7cwdj05s-500x500.jpg",
      quantity: 1,
      deposit: 900,
      delivery: "free",
      category: "bed",
    },
    {
      id: 2,
      title: "Aurora Wooden Queen Bed (6x5)",
      price: {
        threeMonths: 539,
        sixMonths: 439,
        twelveMonths: 339,
      },
      image: "https://p.rmjo.in/productSquare/sm454qim-500x500.jpg",
      quantity: 2,
      deposit: 1000,
      delivery: "free",
      category: "bed",
    },
    {
      id: 3,
      title: "Napster Metal Single Bed (6x3)",
      price: {
        threeMonths: 249,
        sixMonths: 149,
        twelveMonths: 119,
      },
      image: "https://p.rmjo.in/productSquare/z0b45rr0-500x500.jpg",
      quantity: 1,
      deposit: 700,
      delivery: "free",
      category: "bed",
    },
    {
      id: 4,
      title: "Poise Wooden Single Bed (6.5x3)",
      price: {
        threeMonths: 419,
        sixMonths: 319,
        twelveMonths: 219,
      },
      image: "https://p.rmjo.in/productSquare/e5qwec0i-500x500.jpg",
      quantity: 1,
      deposit: 1050,
      delivery: "free",
      category: "bed",
    },
    {
      id: 5,
      title: "Napster Metal Queen Bed (12x6)",
      price: {
        threeMonths: 500,
        sixMonths: 400,
        twelveMonths: 300,
      },
      image: "https://p.rmjo.in/productSquare/7cwdj05s-500x500.jpg",
      quantity: 1,
      deposit: 1200,
      delivery: "free",
      category: "bed",
    },
    {
      id: 6,
      title: "Top Load Washing Machine",
      price: {
        threeMonths: 790,
        sixMonths: 690,
        twelveMonths: 590,
      },
      image: "https://p.rmjo.in/productSquare/6q24nt3v-500x500.jpg",
      quantity: 1,
      deposit: 1400,
      delivery: "free",
      category: "washing-machine",
    },
    {
      id: 7,
      title: "Semi Automatic Washing Machine",
      price: {
        threeMonths: 479,
        sixMonths: 379,
        twelveMonths: 279,
      },
      image: "https://p.rmjo.in/productSquare/8x2o0azg-500x500.jpg",
      quantity: 1,
      deposit: 800,
      delivery: "free",
      category: "washing-machine",
    },
    {
      id: 8,
      title: "Front Load Washing Machine",
      price: {
        threeMonths: 1189,
        sixMonths: 1089,
        twelveMonths: 989,
      },
      image: "https://p.rmjo.in/productSquare/ed9b95oj-500x500.jpg",
      quantity: 1,
      deposit: 2100,
      delivery: "free",
      category: "washing-machine",
    },
    {
      id: 9,
      title: "Double Bed with Fridge and Washing Machine",
      price: {
        threeMonths: 2357,
        sixMonths: 2257,
        twelveMonths: 2157,
      },
      image: "https://p.rmjo.in/productSquare/4c3pll7i-500x500.jpg",
      quantity: 1,
      deposit: 3000,
      delivery: "free",
      category: "washing-machine",
    },
    {
      id: 10,
      title: "TV & Washing Machine Combo",
      price: {
        threeMonths: 1298,
        sixMonths: 1198,
        twelveMonths: 1098,
      },
      image: "https://p.rmjo.in/productSquare/co3fqptc-500x500.jpg",
      quantity: 1,
      deposit: 2200,
      delivery: "free",
      category: "washing-machine",
    },
    {
      id: 11,
      title: "Double Door Fridge & Washing Machine",
      price: {
        threeMonths: 1818,
        sixMonths: 1718,
        twelveMonths: 1618,
      },
      image: "https://p.rmjo.in/productSquare/3lhbfgbu-500x500.jpg",
      quantity: 1,
      deposit: 2500,
      delivery: "free",
      category: "washing-machine",
    },
    {
      id: 12,
      title: "TV with Fridge & Washing Machine",
      price: {
        threeMonths: 3099,
        sixMonths: 2999,
        twelveMonths: 2899,
      },
      image: "https://p.rmjo.in/productSquare/rz1t7cye-500x500.jpg",
      quantity: 1,
      deposit: 4000,
      delivery: "free",
      category: "washing-machine",
    },
    {
      id: 13,
      title: "Double Bed & Washing Machine",
      price: {
        threeMonths: 1088,
        sixMonths: 988,
        twelveMonths: 888,
      },
      image: "https://p.rmjo.in/productSquare/novzayp0-500x500.jpg",
      quantity: 1,
      deposit: 2200,
      delivery: "free",
      category: "washing-machine",
    },
    {
      id: 14,
      title: "Ultima Appliances Combo",
      price: {
        threeMonths: 1597,
        sixMonths: 1497,
        twelveMonths: 1347,
      },
      image: "https://p.rmjo.in/productSquare/ahqsdm86-500x500.jpg",
      quantity: 1,
      deposit: 3100,
      delivery: "free",
      category: "Appliances",
    },
    {
      id: 15,
      title: "Essential Appliances Combo",
      price: {
        threeMonths: 1298,
        sixMonths: 1198,
        twelveMonths: 1098,
      },
      image: "https://p.rmjo.in/productSquare/htxc60er-500x500.jpg",
      quantity: 1,
      deposit: 1800,
      delivery: "free",
      category: "Appliances",
    },
    {
      id: 16,
      title: "Eco 1 BHK",
      price: {
        threeMonths: 768,
        sixMonths: 668,
        twelveMonths: 568,
      },
      image: "https://p.rmjo.in/productSquare/8x2o0azg-500x500.jpg",
      quantity: 1,
      deposit: 1200,
      delivery: "free",
      category: "house",
    },
    {
      id: 17,
      title: "OnePlus 7 (Mirror Gray)",
      price: {
        threeMonths: 1109,
        sixMonths: 1099,
        twelveMonths: 999,
      },
      image: "https://p.rmjo.in/moodShot/zorunxgt-1024x512.jpg",
      quantity: 1,
      deposit: 2549,
      delivery: "free",
      category: "smartphones",
    },
    {
      id: 18,
      title: "Queen Foam Mattress (6x5)",
      price: {
        threeMonths: 399,
        sixMonths: 299,
        twelveMonths: 199,
      },
      image: "https://p.rmjo.in/productSquare/zuilc4mr-500x500.jpg",
      quantity: 1,
      deposit: 453,
      delivery: "free",
      category: "mattresses",
    },
    {
      id: 19,
      title: "Single Coir and Foam Mattress (6x3)",
      price: {
        threeMonths: 299,
        sixMonths: 159,
        twelveMonths: 99,
      },
      image: "https://p.rmjo.in/productSquare/bbqhhykq-500x500.jpg",
      quantity: 1,
      deposit: 199,
      delivery: "free",
      category: "mattresses",
    },
    {
      id: 20,
      title: "Single Foam Mattress (6x3)",
      price: {
        threeMonths: 699,
        sixMonths: 599,
        twelveMonths: 499,
      },
      image: "https://p.rmjo.in/moodShot/bjkbu237-1024x512.jpg",
      quantity: 1,
      deposit: 444,
      delivery: "free",
      category: "mattresses",
    },
    {
      id: 21,
      title: "King Coir & Foam Mattress (6.6x6)",
      price: {
        threeMonths: 819,
        sixMonths: 678,
        twelveMonths: 598,
      },
      image: "https://p.rmjo.in/productSquare/63ua3tco-500x500.jpg",
      quantity: 1,
      deposit: 649,
      delivery: "free",
      category: "mattresses",
    },
    {
      id: 22,
      title: "Single XL Coir & Foam Mattress (6.6x3)",
      price: {
        threeMonths: 4689,
        sixMonths: 3689,
        twelveMonths: 2689,
      },
      image: "https://p.rmjo.in/productSquare/8x2o0azg-500x500.jpg",
      quantity: 1,
      deposit: 1257,
      delivery: "free",
      category: "mattresses",
    },
    {
      id: 23,
      title: "Single Spring Mattress (6x3)",
      price: {
        threeMonths: 768,
        sixMonths: 657,
        twelveMonths: 583,
      },
      image: "https://p.rmjo.in/moodShot/o83l2ucm-1024x512.jpg",
      quantity: 1,
      deposit: 540,
      delivery: "free",
      category: "mattresses",
    },
    {
      id: 24,
      title: "Set Of 2 Single Foam Mattress (6x3)",
      price: {
        threeMonths: 657,
        sixMonths: 600,
        twelveMonths: 546,
      },
      image: "https://p.rmjo.in/moodShot/yyljse85-1024x512.jpg",
      quantity: 1,
      deposit: 419,
      delivery: "free",
      category: "mattresses",
    },
    {
      id: 25,
      title: "Stowy 2-Door Wardrobe",
      price: {
        threeMonths: 976,
        sixMonths: 876,
        twelveMonths: 776,
      },
      image: "https://p.rmjo.in/moodShot/qpaqpi6f-1024x512.jpg",
      quantity: 1,
      deposit: 629,
      delivery: "free",
      category: "wardrobe",
    },
    {
      id: 26,
      title: "Hutch 2-Door Wardrobe",
      price: {
        threeMonths: 934,
        sixMonths: 754,
        twelveMonths: 654,
      },
      image: "https://p.rmjo.in/moodShot/21bgcpb2-1024x512.jpg",
      quantity: 1,
      deposit: 639,
      delivery: "free",
      category: "wardrobe",
    },
    {
      id: 27,
      title: "Magnum 2-Door Wardrobe",
      price: {
        threeMonths: 834,
        sixMonths: 734,
        twelveMonths: 643,
      },
      image: "https://p.rmjo.in/moodShot/hl4fx01m-1024x512.jpg",
      quantity: 1,
      deposit: 699,
      delivery: "free",
      category: "wardrobe",
    },
    {
      id: 28,
      title: "Magnum 3-Door Wardrobe",
      price: {
        threeMonths: 3684,
        sixMonths: 3547,
        twelveMonths: 3342,
      },
      image: "https://p.rmjo.in/moodShot/rs76ni8t-1024x512.jpg",
      quantity: 1,
      deposit: 1109,
      delivery: "free",
      category: "wardrobe",
    },
    {
      id: 29,
      title: "Magnum 1-Door Wardrobe",
      price: {
        threeMonths: 512,
        sixMonths: 412,
        twelveMonths: 312,
      },
      image: "https://p.rmjo.in/moodShot/m0opadeb-1024x512.jpg",
      quantity: 1,
      deposit: 409,
      delivery: "free",
      category: "wardrobe",
    },
    {
      id: 30,
      title: "Kipper 2-Door Wardrobe",
      price: {
        threeMonths: 923,
        sixMonths: 823,
        twelveMonths: 723,
      },
      image: "https://p.rmjo.in/moodShot/t0vosrkz-1024x512.jpg",
      quantity: 1,
      deposit: 899,
      delivery: "free",
      category: "wardrobe",
    },
    {
      id: 31,
      title: "Apple iPhone XR 64GB (Black)",
      price: {
        threeMonths: 5213,
        sixMonths: 5113,
        twelveMonths: 5013,
      },
      image: "https://p.rmjo.in/moodShot/a0y3f9ck-1024x512.jpg",
      quantity: 1,
      deposit: 4249,
      delivery: "free",
      category: "smartphones",
    },
    {
      id: 32,
      title: "OnePlus 7 Pro (Mirror Gray)",
      price: {
        threeMonths: 4678,
        sixMonths: 4578,
        twelveMonths: 4478,
      },
      image: "https://p.rmjo.in/moodShot/q5l5kxcl-1024x512.jpg",
      quantity: 1,
      deposit: 3849,
      delivery: "free",
      category: "smartphones",
    },
    {
      id: 33,
      title: "Samsung Galaxy Note 10 (Aura Black)",
      price: {
        threeMonths: 6378,
        sixMonths: 6278,
        twelveMonths: 6178,
      },
      image: "https://p.rmjo.in/moodShot/dem5mxy3-1024x512.jpg",
      quantity: 1,
      deposit: 5149,
      delivery: "free",
      category: "smartphones",
    },
    {
      id: 34,
      title: "OnePlus 7T ( Frosted Silver )",
      price: {
        threeMonths: 3584,
        sixMonths: 3484,
        twelveMonths: 3384,
      },
      image: "https://p.rmjo.in/moodShot/xbdyaob0-1024x512.jpg",
      quantity: 1,
      deposit: 2999,
      delivery: "free",
      category: "smartphones",
    },
    {
      id: 35,
      title: "Apple iPhone X (Silver)",
      price: {
        threeMonths: 49900,
        sixMonths: 47900,
        twelveMonths: 45900,
      },
      image: "https://p.rmjo.in/moodShot/itcyqn02-1024x512.jpg",
      quantity: 1,
      deposit: 11999,
      delivery: "free",
      category: "smartphones",
    },
    {
      id: 36,
      title: "Samsung Galaxy S9 (Black)",
      price: {
        threeMonths: 22999,
        sixMonths: 21999,
        twelveMonths: 20999,
      },
      image: "https://p.rmjo.in/moodShot/jp7qwmw5-1024x512.jpg",
      quantity: 1,
      deposit: 7999,
      delivery: "free",
      category: "smartphones",
    },
    {
      id: 37,
      title: "Motorized Treadmill AF 517",
      price: {
        threeMonths: 1599,
        sixMonths: 1499,
        twelveMonths: 1399,
      },
      image: "https://p.rmjo.in/moodShot/013zekxo-1024x512.jpg",
      quantity: 1,
      deposit: 3649,
      delivery: "free",
      category: "threadmills",
    },
    {
      id: 38,
      title: "Cross Trainer With Seat",
      price: {
        threeMonths: 7584,
        sixMonths: 7484,
        twelveMonths: 7384,
      },
      image: "https://p.rmjo.in/moodShot/aak3eoor-1024x512.jpg",
      quantity: 1,
      deposit: 2829,
      delivery: "free",
      category: "crosstrainers",
    },
    {
      id: 39,
      title: "Exercise Cycle AB-100",
      price: {
        threeMonths: 6840,
        sixMonths: 6740,
        twelveMonths: 6540,
      },
      image: "https://p.rmjo.in/moodShot/wlb98aev-1024x512.jpg",
      quantity: 1,
      deposit: 3658,
      delivery: "free",
      category: "exercisebikes",
    },
  ],
};

function testingObjectValue(initialState) {
  const makeAnArray = Object.values(initialState);
  //console.log(makeAnArray);
  const titlePrint = makeAnArray[0].reduce((acc, curr, index) => {
    console.log(curr.price.threeMonths);
  }, []);
}
console.log(testingObjectValue(initialState));
